volumes:
  mongo_data:
    driver: local

networks:
  net:
    driver: bridge

services:
  backend:
    build: ./backend
    environment:
      MONGO_URI: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017"
      CONFIG_PATH: ${BACKEND_CONFIG_PATH}
    depends_on:
      - mongodb
    volumes:
      - ./backend/logs:/logs
    networks:
      - net

  frontend:
    build: ./frontend
    depends_on:
      - backend
    networks:
      - net

  proxy:
    image: nginx:1.27.4-alpine3.21
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./proxy.nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - net

  mongodb:
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - net
    restart: unless-stopped
    command: mongod --logpath /dev/null
