run:
  timeout: 3m
  tests: true

linters:
  enable:
    - gosimple
    - gocritic
    - gofmt
    - errcheck
    - govet
    - staticcheck
    - unused

linters-settings:
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck