// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/moevm/nosql1h25-writer/backend/internal/service/orders (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination mocks/mock_contract.go -package=mocks . Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/moevm/nosql1h25-writer/backend/internal/entity"
	orders "github.com/moevm/nosql1h25-writer/backend/internal/service/orders"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockService) Create(ctx context.Context, in orders.CreateIn) (primitive.ObjectID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(primitive.ObjectID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), ctx, in)
}

// Find mocks base method.
func (m *MockService) Find(ctx context.Context, offset, limit int, minCost, maxCost *int, sortBy *string) (orders.FindOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, offset, limit, minCost, maxCost, sortBy)
	ret0, _ := ret[0].(orders.FindOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockServiceMockRecorder) Find(ctx, offset, limit, minCost, maxCost, sortBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockService)(nil).Find), ctx, offset, limit, minCost, maxCost, sortBy)
}

// GetByID mocks base method.
func (m *MockService) GetByID(ctx context.Context, id primitive.ObjectID) (orders.OrderWithClientData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(orders.OrderWithClientData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockService)(nil).GetByID), ctx, id)
}

// GetByIDExt mocks base method.
func (m *MockService) GetByIDExt(ctx context.Context, id primitive.ObjectID) (entity.OrderExt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDExt", ctx, id)
	ret0, _ := ret[0].(entity.OrderExt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDExt indicates an expected call of GetByIDExt.
func (mr *MockServiceMockRecorder) GetByIDExt(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDExt", reflect.TypeOf((*MockService)(nil).GetByIDExt), ctx, id)
}

// Response mocks base method.
func (m *MockService) Response(ctx context.Context, orderID, userID primitive.ObjectID) (primitive.ObjectID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Response", ctx, orderID, userID)
	ret0, _ := ret[0].(primitive.ObjectID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Response indicates an expected call of Response.
func (mr *MockServiceMockRecorder) Response(ctx, orderID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Response", reflect.TypeOf((*MockService)(nil).Response), ctx, orderID, userID)
}
