name: Generate Swagger Docs

on:
  push:
    branches: [ "main" ]
    paths: [ "internal/api/**", "internal/app/app.go" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "internal/api/**", "internal/app/app.go" ]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        working-directory: backend

    - name: Install dependencies
      working-directory: backend
      run: go mod tidy

    - name: Generate Swagger Docs And Format Comments
      working-directory: backend
      run: make swag

    - name: Commit Swagger Docs
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add /docs /internal
        git commit -m 'Update Swagger docs and formatting' || echo 'No changes'
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
